### ISSUE TITLE
Line Spacing

### ISSUE THREAD

**Issue by Courtney4597** [Courtney4597/CDGD304-01#6]
How do I change the line spacing between elements, like between a h1 and h3

**Comment by saulbaizman** [comment]
Line spacing in between lines of text, such as in a paragraph, are handled
through the ‘line-height’ property. That’s the equivalent of leading in
print.

If you’re talking about adjusting the white space above and below <h1> and
<h3> elements, then you’ll want to refer to the box model. Tweak the
‘padding’ and ‘margin’ properties.
